// This file was generated by Mendix Modeler 6.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testsuite.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the TestSuite module
	public static java.util.List<testsuite.proxies.FAQ> dS_GetFAQ(IContext context, testsuite.proxies.CurrentPage _currentPage)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("CurrentPage", _currentPage == null ? null : _currentPage.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "TestSuite.DS_GetFAQ", params);
			java.util.List<testsuite.proxies.FAQ> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<testsuite.proxies.FAQ>();
				for (IMendixObject obj : objs)
					result.add(testsuite.proxies.FAQ.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oCh_GetFAQ(IContext context, testsuite.proxies.CurrentPage _currentPage)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("CurrentPage", _currentPage == null ? null : _currentPage.getMendixObject());
			Core.execute(context, "TestSuite.OCh_GetFAQ", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}