// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testsuite.proxies;

public class FAQ
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject fAQMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestSuite.FAQ";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Nr("Nr"),
		Question("Question"),
		Answer("Answer"),
		FAQ_Page("TestSuite.FAQ_Page");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FAQ(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestSuite.FAQ"));
	}

	protected FAQ(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fAQMendixObject)
	{
		if (fAQMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TestSuite.FAQ", fAQMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestSuite.FAQ");

		this.fAQMendixObject = fAQMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'FAQ.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static testsuite.proxies.FAQ initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testsuite.proxies.FAQ.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static testsuite.proxies.FAQ initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testsuite.proxies.FAQ(context, mendixObject);
	}

	public static testsuite.proxies.FAQ load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testsuite.proxies.FAQ.initialize(context, mendixObject);
	}

	public static java.util.List<testsuite.proxies.FAQ> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testsuite.proxies.FAQ> result = new java.util.ArrayList<testsuite.proxies.FAQ>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TestSuite.FAQ" + xpathConstraint))
			result.add(testsuite.proxies.FAQ.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Nr
	 */
	public final Integer getNr()
	{
		return getNr(getContext());
	}

	/**
	 * @param context
	 * @return value of Nr
	 */
	public final Integer getNr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.Nr.toString());
	}

	/**
	 * Set value of Nr
	 * @param nr
	 */
	public final void setNr(Integer nr)
	{
		setNr(getContext(), nr);
	}

	/**
	 * Set value of Nr
	 * @param context
	 * @param nr
	 */
	public final void setNr(com.mendix.systemwideinterfaces.core.IContext context, Integer nr)
	{
		getMendixObject().setValue(context, MemberNames.Nr.toString(), nr);
	}

	/**
	 * @return value of Question
	 */
	public final String getQuestion()
	{
		return getQuestion(getContext());
	}

	/**
	 * @param context
	 * @return value of Question
	 */
	public final String getQuestion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Question.toString());
	}

	/**
	 * Set value of Question
	 * @param question
	 */
	public final void setQuestion(String question)
	{
		setQuestion(getContext(), question);
	}

	/**
	 * Set value of Question
	 * @param context
	 * @param question
	 */
	public final void setQuestion(com.mendix.systemwideinterfaces.core.IContext context, String question)
	{
		getMendixObject().setValue(context, MemberNames.Question.toString(), question);
	}

	/**
	 * @return value of Answer
	 */
	public final String getAnswer()
	{
		return getAnswer(getContext());
	}

	/**
	 * @param context
	 * @return value of Answer
	 */
	public final String getAnswer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Answer.toString());
	}

	/**
	 * Set value of Answer
	 * @param answer
	 */
	public final void setAnswer(String answer)
	{
		setAnswer(getContext(), answer);
	}

	/**
	 * Set value of Answer
	 * @param context
	 * @param answer
	 */
	public final void setAnswer(com.mendix.systemwideinterfaces.core.IContext context, String answer)
	{
		getMendixObject().setValue(context, MemberNames.Answer.toString(), answer);
	}

	/**
	 * @return value of FAQ_Page
	 */
	public final testsuite.proxies.Page getFAQ_Page() throws com.mendix.core.CoreException
	{
		return getFAQ_Page(getContext());
	}

	/**
	 * @param context
	 * @return value of FAQ_Page
	 */
	public final testsuite.proxies.Page getFAQ_Page(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testsuite.proxies.Page result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FAQ_Page.toString());
		if (identifier != null)
			result = testsuite.proxies.Page.load(context, identifier);
		return result;
	}

	/**
	 * Set value of FAQ_Page
	 * @param faq_page
	 */
	public final void setFAQ_Page(testsuite.proxies.Page faq_page)
	{
		setFAQ_Page(getContext(), faq_page);
	}

	/**
	 * Set value of FAQ_Page
	 * @param context
	 * @param faq_page
	 */
	public final void setFAQ_Page(com.mendix.systemwideinterfaces.core.IContext context, testsuite.proxies.Page faq_page)
	{
		if (faq_page == null)
			getMendixObject().setValue(context, MemberNames.FAQ_Page.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.FAQ_Page.toString(), faq_page.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return fAQMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testsuite.proxies.FAQ that = (testsuite.proxies.FAQ) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestSuite.FAQ";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
